version: "3.9"

services:
  api:
    container_name: BankingSystemAPI
    build:
      context: .
      dockerfile: BankingSystem.API/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/data/bankingsystem.db
    volumes:
      - ./data:/data
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: RedisCache
    ports:
      - "6379:6379"
    restart: unless-stopped
